apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 20001
      targetPort: 20001
  selector:
    app: kiali
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  template:
    metadata:
      labels:
        app: kiali
    spec:
      containers:
        - name: kiali
          image: quay.io/kiali/kiali:v1.65
          ports:
            - containerPort: 20001
          env:
            - name: ACTIVE_NAMESPACE
              value: "default"
            - name: PROMETHEUS_URL
              value: "http://prometheus.istio-system.svc.cluster.local:9090"